"$schema" = 'https://starship.rs/config-schema.json'

format = '$directory'

[directory.substitutions]
'/' = '  '

[directory]
truncate_to_repo = false
format = '[$path]($style)[](#1abc9c) '
use_os_path_sep = false
style = 'bold fg:#000000 bg:#1abc9c'
