
[fonts.variables]
monoFont = "Liga SFMono Nerd Font"
monoFontSize = 18

[core]
depends = ["fonts"]

[core.files]
"lf/lf.sh" = "~/.config/lf/lfrc"
lf = "~/.config/lf"
lsd = "~/.config/lsd"
starship = "~/.config"
wezterm = "~/.config/wezterm"

[linux]
depends = ["fonts"]

[linux.files]
fonts = "~/.local/share/fonts"
git = "~/"
yay = "~/.config/yay"
"zsh/.zshenv" = "~/.zshenv"
