
[fonts.variables]
monoFont = "Liga SFMono Nerd Font"
monoFontSize = 18

[core]
depends = ["fonts"]

[core.files]
"lf/lf.sh" = "~/.config/lfrc"
lf = "~/.config/lf"
starship = "~/.config"
wezterm = "~/.config/wezterm"
