[colors.variables]
blueMedium = "#0091f8"
greenBright = "#00ffcc"
grayDark = "#1f2335"
gray = "#b8bdd1"
white = "#ffffff"
black = "#000000"
magentaBright = "#ff007c"

[fonts.variables]
displayFont = "SF Pro Rounded"
displayFontSize = 16
monoFont = "CommitMono Nerd Font"
# monoFont = "Liga SFMono Nerd Font"
# monoFont = "CommitMono"
# monoFont = "Myosevka"
# monoFont = "IosevkaTerm Nerd Font"
monoFontSize = 16

[core]
depends = ["colors", "fonts"]

[core.files]
"lf/lf.sh" = "~/.config/lf/lfrc"
lf = "~/.config/lf"
starship = "~/.config"
wezterm = "~/.config/wezterm"

[linux]
depends = ["fonts"]

[linux.files]
fonts = { target = "~/.local/share/fonts", type = "symbolic" }
kitty = "~/.config/kitty"
lsd = "~/.config/lsd"
git = "~/"
sway = "~/.config/sway"
waybar = "~/.config/waybar"
wpaperd = "~/.config/wpaperd"
yay = { target = "~/.config/yay", type = "symbolic" }
yofi = { target = "~/.config/yofi", type = "template" }
"zsh/.zshenv" = "~/.zshenv"

[helpers]
hex2rgb = ".dotter/helpers/hex2rgb.rhai"
